### ISSUE TITLE
To Do-List

### ISSUE THREAD

**Issue by TheNerd123** [TheNerd123/Mandelbrot-Set-Project-prototype#2]
1. Find a font that fits the project
2. Get started and finish the LoadText, and iterationsToRGB function
3. Finish the UpdateRender function
4. Finish Main.cpp
5. Functions that needs to be checked: mapPixelsToCoords and CountIterations
6. Check the enum thingy in the .h file because there's no way I'm doing that right

**Comment by domoago** [comment]
Completed
